services:
  spring.boot.crud.sample:
    image: ddewaele/springboot.crud.sample
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employee_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  db:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
