spring:
  datasource:
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      data-source-properties:
        wrapperPlugins: iam,failover
        iamRegion: eu-central-1
        failoverMode: strict-reader
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  sql:
    init:
      platform: POSTGRESQL