spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: employee_db_user
    password: employee_db_user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: POSTGRESQL

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
